### ISSUE TITLE
JDBC monitoring not working with Liferay 7.4+

### ISSUE THREAD

**Issue by bitsky6** [javamelody/liferay-javamelody#28]
Currently testing with Liferay 7.4.3.132 GA132 all works fine except the JDBC monitoring.
Using Java 21 and Gradle.

I have tested with latest version no luck.

**Comment by evernat** [comment]
Have you read _Sql monitoring_ for Liferay 7 at https://github.com/javamelody/javamelody/wiki/LiferayPlugin#sql-monitoring ?

**Comment by bitsky6** [comment]
Yes I did it is what I used until Liferay 7.4

After doing many test and try I believe the issue is that since latest tomcat 9 don't allow anymore jdbc rewrap as it is only read-only.

Sì I could not find a way to make it work.

If anyone know how to would appreciate it.

**Comment by evernat** [comment]
> After doing many test and try I believe the issue is that since latest tomcat 9 don't allow anymore jdbc rewrap as it is only read-only.

No, this issue is not related to Tomcat 9.

The issue is related to shielded classloader of Liferay, which does not allow to look into JNDI. See https://liferay.dev/b/setting-up-jndi-in-liferay-7-4
The solution is to go around the shielded classloader as said by Liferay in the linked page above.

**Comment by evernat** [comment]
fixed by 2202358

**Comment by bitsky6** [comment]
This issue was not fixed, I do can connect to JNDI fine after adjusting to go around the shielded container. The issue is java melody not able to rewrap so that it can actually monitor it.

**Comment by evernat** [comment]
Can you give the debugging logs, which you can find at the bottom of the monitoring page and which starts with `DEBUG JavaMelody filter init started` ?

**Comment by evernat** [comment]
And to be sure, you have rebuilt and redeployed this liferay hook to use the 2202358 commit that fixes the issue ?

(I can rebuild it for you if needed)

**Comment by bitsky6** [comment]
Hello Evernat, please make me a build if possible and then can try to test it.
Thanks

**Comment by bitsky6** [comment]
Here are the logs

Fri Nov 14 15:23:25 GMT 2025     DEBUG     JavaMelody filter init started
Fri Nov 14 15:23:25 GMT 2025     DEBUG     OS: Linux null, amd64/64
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Java: OpenJDK Runtime Environment, 21.0.8+9-LTS
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Server: Apache Tomcat/9.0.98
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Webapp context:
Fri Nov 14 15:23:25 GMT 2025     DEBUG     JavaMelody version: 1.99.2
Fri Nov 14 15:23:25 GMT 2025     DEBUG     JavaMelody classes loaded from: file:/opt/liferay-portal/osgi/state/org.eclipse.osgi/1447/0/bundleFile
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Application type: Liferay
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Application version: null
Fri Nov 14 15:23:25 GMT 2025     DEBUG     Host: xc-xmp-app@172.16.25.4
Fri Nov 14 15:23:25 GMT 2025     DEBUG     parameter defined: sql-transform-pattern=\([\?, ]+\)
Fri Nov 14 15:23:25 GMT 2025     DEBUG     parameter defined: displayed-counters=http,sql,error,log
Fri Nov 14 15:23:25 GMT 2025     DEBUG     parameter defined: datasources=java:comp/env/jdbc/LiferayPool
Fri Nov 14 15:23:25 GMT 2025     DEBUG     parameter defined: rewrap-datasources=true
Fri Nov 14 15:23:25 GMT 2025     DEBUG     log listeners initialized
Fri Nov 14 15:23:25 GMT 2025     DEBUG     rebinding datasources failed, skipping
Fri Nov 14 15:23:25 GMT 2025     DEBUG     JPA persistence provider resolver initialized
Fri Nov 14 15:23:25 GMT 2025     DEBUG     counters initialized
Fri Nov 14 15:23:26 GMT 2025     DEBUG     counters data read from files in /opt/liferay/tomcat/temp/javamelody/_xc-xmp-app
Fri Nov 14 15:23:26 GMT 2025     DEBUG     collect task scheduled every 60s
Fri Nov 14 15:23:26 GMT 2025     DEBUG     first collect of data done
Fri Nov 14 15:23:26 GMT 2025     DEBUG     JavaMelody filter init done in 1019 ms
Fri Nov 14 15:23:26 GMT 2025     DEBUG     JavaMelody is monitoring Liferay
Sat Nov 15 00:00:31 GMT 2025     DEBUG     Obsolete files deleted. JavaMelody disk usage: 33567 KB
Sun Nov 16 00:00:11 GMT 2025     DEBUG     Obsolete files deleted. JavaMelody disk usage: 33568 KB
Mon Nov 17 00:00:35 GMT 2025     DEBUG     Obsolete files deleted. JavaMelody disk usage: 33569 KB
Tue Nov 18 00:00:51 GMT 2025     DEBUG     Obsolete files deleted. JavaMelody disk usage: 33574 KB

**Comment by evernat** [comment]
@bitsky6 sorry for the dealy. 
I have made a build including the fix. You can download it at : 
http://javamelody.org/downloads/liferay-javamelody-hook-1.99.2.1.war

**Comment by bitsky6** [comment]
Hey @evernat 

I just tested and now works again fine the sql monitoring thanks for that.
Only the JNDI tree button loads a white page not showing anything and is missing the datasources tab but monitoring works fine now for SQL. Thanks for that.

<img width="1216" height="273" alt="Image" src="https://github.com/user-attachments/assets/4a4dc4be-c4ce-4785-9e91-62eea7788d06" />
